"""
services/recommendation.py
===========================
College Recommendation Engine
------------------------------
Accepts a validated student profile and returns a ranked, classified
list of college recommendations drawn from the local dataset.

Algorithm
---------
1. Validate the student profile — raise ValueError for bad input.
2. Load and hard-filter the dataset:
      - category == student category
      - cutoff_percentile <= student CET percentile  (only eligible rows)
3. Score every eligible row on SIX independent dimensions (total 100 pts):

   Dimension                Weight  Notes
   ─────────────────────────────────────────────────────────────────────
   Cutoff Proximity         30 pts  Exponential decay; closest gap = max
   Branch Match             30 pts  Exact=30, partial word overlap=15
   City Match               15 pts  Exact city name match
   Placement Quality        12 pts  Scaled against dataset max avg LPA
   NAAC Grade               8 pts   A+=8, A=5, B++=3, B+=2, B=1, else 0
   Category Eligibility     5 pts   Flat bonus confirming valid eligibility
   ─────────────────────────────────────────────────────────────────────
   Total                    100 pts

4. Classify into recommendation tiers by cutoff gap:

   Dream    — student percentile is only  0 – 3  pts above cutoff
               (college is a stretch; admission is uncertain)
   Moderate — student percentile is  3 – 10 pts above cutoff
               (realistic, well-matched choice)
   Safe     — student percentile is  > 10 pts above cutoff
               (high admission probability)

5. Sort by total score descending; return the top 10.

6. Each returned dict includes:
   - reason : short rule-based explanation (always available, no API call)
   - ai_explanation : personalised sentence generated by IBM Watsonx Granite
                      using only that single college's data; falls back to
                      the rule-based reason on any API failure.

Public API
----------
    get_recommendations(student_data) → dict[str, Any]
    validate_profile(student_data)    → None  (raises ValueError on bad input)
"""

from __future__ import annotations

import logging
from typing import Any, cast

import pandas as pd

from services.dataset import (
    load_dataset,
    COL_ID, COL_NAME, COL_CITY, COL_BRANCH, COL_CATEGORY,
    COL_CUTOFF, COL_FEES,
)
from services.watsonx import chat, summarize_recommendations

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Scoring weights  (must sum to 100)
# ---------------------------------------------------------------------------
W_CUTOFF_PROXIMITY: int = 40   # How close the college cutoff is to the student
W_BRANCH_MATCH:     int = 35   # Preferred branch alignment
W_CITY_MATCH:       int = 20   # Preferred city match
W_CATEGORY:         int = 5    # Flat eligibility confirmation bonus

assert W_CUTOFF_PROXIMITY + W_BRANCH_MATCH + W_CITY_MATCH + W_CATEGORY == 100

# ---------------------------------------------------------------------------
# Tier thresholds  (based on student_percentile − college_cutoff)
# ---------------------------------------------------------------------------
DREAM_MAX_GAP:    float = 3.0    # 0 < gap ≤ 3   → Dream
MODERATE_MAX_GAP: float = 10.0   # 3 < gap ≤ 10  → Moderate
# gap > 10 → Safe

# Normalisation constant for cutoff proximity:
# a gap equal to _PROXIMITY_SCALE maps to ~0 pts
_PROXIMITY_SCALE: float = 20.0

# Maximum result set
TOP_N: int = 10

# Valid reservation categories accepted from student profiles
_VALID_CATEGORIES: frozenset[str] = frozenset(
    {"OPEN", "OBC", "SC", "ST", "VJ", "NT1", "NT2", "NT3", "SBC", "EWS"}
)


# ===========================================================================
# Public entry-point
# ===========================================================================

def get_recommendations(student_data: dict[str, Any]) -> dict[str, Any]:
    """
    Return a ranked list of college recommendations for the given student.

    Parameters
    ----------
    student_data : dict
        Required keys:
          name             (str)   Student's name
          cet_percentile   (float) MHT-CET overall percentile (0–100)
          category         (str)   Reservation category, e.g. "OPEN", "OBC"
          preferred_branch (str)   Desired branch, e.g. "Computer Engineering"
          preferred_city   (str)   Desired city, e.g. "Pune"

    Returns
    -------
    dict
        Keys:
          recommendations : list[dict]  Up to TOP_N college records with keys
                            name, branch, city, cutoff, annual_fees, avg_package,
                            naac_grade, recommendation_category, match_score,
                            reason, ai_explanation
          summary         : str  AI-generated overall advisory paragraph
    """
    logger.info(
        "get_recommendations | name=%s pct=%.2f cat=%s branch=%s city=%s",
        student_data.get("name"),
        float(student_data.get("cet_percentile", 0)),
        student_data.get("category"),
        student_data.get("preferred_branch"),
        student_data.get("preferred_city"),
    )

    # 1. Validate
    validate_profile(student_data)

    percentile       = float(student_data["cet_percentile"])
    category         = student_data["category"].strip().upper()
    preferred_branch = student_data["preferred_branch"].strip()
    preferred_city   = student_data["preferred_city"].strip()

    # 2. Load and hard-filter (only rows the student is eligible for)
    df = load_dataset()
    if df.empty:
        logger.warning("Dataset is empty — cannot generate recommendations.")
        return {"recommendations": [], "summary": ""}

    eligible = df[
        (df[COL_CATEGORY].str.upper() == category)
        & (df[COL_CUTOFF] <= percentile)
    ].copy()

    if eligible.empty:
        logger.info("No eligible colleges for pct=%.2f cat=%s.", percentile, category)
        return {"recommendations": [], "summary": ""}

    # 3. Score every eligible row
    eligible["_score"] = eligible.apply(
        lambda row: _compute_score(
            row, percentile, preferred_branch, preferred_city
        ),
        axis=1,
    )

    # 4. Classify into Dream / Moderate / Safe tiers
    eligible["_tier"] = cast(pd.Series, eligible[COL_CUTOFF]).map(
        lambda cutoff: _classify_tier(percentile - float(cutoff))
    )

    # 5. Sort and slice top N
    top = (
        eligible
        .sort_values(by="_score", ascending=False)  # type: ignore[call-overload]
        .head(TOP_N)
        .reset_index(drop=True)
    )

    # 6. Build result dicts (rule-based reason first, AI explanation added next)
    results: list[dict[str, Any]] = []
    for _, row in top.iterrows():
        results.append(
            _build_result(row, percentile, preferred_branch, preferred_city)
        )

    # 7. Generate per-college AI explanation (one Watsonx call per college)
    results = _attach_ai_explanations(results, student_data)

    logger.info("Returning %d recommendations for '%s'.", len(results), student_data.get("name"))

    # 8. Overall AI summary (existing watsonx helper)
    summary = summarize_recommendations(student_data, results)

    return {"recommendations": results, "summary": summary}


# ===========================================================================
# Profile validation
# ===========================================================================

def validate_profile(student_data: dict[str, Any]) -> None:
    """
    Validate the student profile dict.
    Raises ValueError with a descriptive message on the first failing check.
    """
    required = {
        "name":             "Student name",
        "cet_percentile":   "CET percentile",
        "category":         "Reservation category",
        "preferred_branch": "Preferred branch",
        "preferred_city":   "Preferred city",
    }
    for key, label in required.items():
        value = student_data.get(key)
        if value is None or str(value).strip() == "":
            raise ValueError(f"{label} is required but was not provided.")

    try:
        pct = float(student_data["cet_percentile"])
    except (TypeError, ValueError):
        raise ValueError(
            f"CET percentile must be a number; got '{student_data['cet_percentile']}'."
        )
    if not (0.0 <= pct <= 100.0):
        raise ValueError(f"CET percentile must be between 0 and 100; got {pct}.")

    cat = str(student_data["category"]).strip().upper()
    if cat not in _VALID_CATEGORIES:
        raise ValueError(
            f"Unknown category '{cat}'. "
            f"Valid options: {', '.join(sorted(_VALID_CATEGORIES))}."
        )


# ===========================================================================
# Scoring  (all private)
# ===========================================================================

def _compute_score(
    row: Any,
    student_percentile: float,
    preferred_branch: str,
    preferred_city: str,
) -> float:
    """
    Compute a 0–100 composite match score for one dataset row.

    Dimensions
    ----------
    Cutoff Proximity  (0–40)
        Linear decay: score = W * max(0, 1 − gap / _PROXIMITY_SCALE).
        Colleges very close to the student's percentile rank highest.

    Branch Match  (0–35)
        Exact match → 35 pts.
        Partial word overlap → 17.5 pts.
        No match → 0 pts.

    City Match  (0–20)
        Exact city name match → 20 pts.

    Category Eligibility  (0–5)
        Flat +5 confirming the row passed the hard category filter.
    """
    gap = student_percentile - float(row[COL_CUTOFF])

    # Cutoff proximity
    proximity = W_CUTOFF_PROXIMITY * max(0.0, 1.0 - gap / _PROXIMITY_SCALE)

    # Branch match
    branch_pts = _score_branch(str(row[COL_BRANCH]), preferred_branch)

    # City match
    city_pts = _score_city(str(row[COL_CITY]), preferred_city)

    # Category eligibility bonus (always earned since we pre-filtered)
    category_pts = float(W_CATEGORY)

    total = proximity + branch_pts + city_pts + category_pts
    return round(min(total, 100.0), 2)


def _score_branch(college_branch: str, preferred_branch: str) -> float:
    """Return branch sub-score: 30 (exact), 15 (partial), or 0."""
    cb = college_branch.lower().strip()
    pb = preferred_branch.lower().strip()
    if cb == pb:
        return float(W_BRANCH_MATCH)
    # Exclude words that appear in almost every branch name — they carry no signal
    stop = {"and", "of", "in", "the", "&", "engineering", "technology", "science"}
    overlap = (set(cb.split()) - stop) & (set(pb.split()) - stop)
    if overlap:
        return float(W_BRANCH_MATCH) / 2.0
    return 0.0


def _score_city(college_city: str, preferred_city: str) -> float:
    """Return city sub-score: 15 (exact) or 0."""
    if college_city.lower().strip() == preferred_city.lower().strip():
        return float(W_CITY_MATCH)
    return 0.0


def _classify_tier(gap: float) -> str:
    """
    Map (student_percentile − college_cutoff) to a tier label.

    Dream    — gap ∈ (0, DREAM_MAX_GAP]
    Moderate — gap ∈ (DREAM_MAX_GAP, MODERATE_MAX_GAP]
    Safe     — gap > MODERATE_MAX_GAP
    """
    if gap <= DREAM_MAX_GAP:
        return "Dream"
    if gap <= MODERATE_MAX_GAP:
        return "Moderate"
    return "Safe"


# ===========================================================================
# Result builder
# ===========================================================================

def _build_result(
    row: Any,
    student_percentile: float,
    preferred_branch: str,
    preferred_city: str,
) -> dict[str, Any]:
    """
    Convert a scored DataFrame row into the public recommendation dict.

    The ``reason`` field is a deterministic rule-based sentence, always
    available without any API call.  ``ai_explanation`` starts empty and
    is filled in by ``_attach_ai_explanations``.
    """
    college_id   = str(row[COL_ID])
    college_name = str(row[COL_NAME])
    branch       = str(row[COL_BRANCH])
    city         = str(row[COL_CITY])
    cutoff       = float(row[COL_CUTOFF])
    fees         = int(row[COL_FEES])
    tier         = str(row["_tier"])
    score        = float(row["_score"])
    gap          = round(student_percentile - cutoff, 2)

    return {
        # ── fields consumed by the template ───────────────────────────
        "college_id":              college_id,
        "name":                    college_name,
        "branch":                  branch,
        "city":                    city,
        "cutoff":                  cutoff,
        "annual_fees":             fees,
        "naac_grade":              "N/A",
        "recommendation_category": tier,
        "match_score":             score,
        # rule-based reason (template renders this as `college.reason`)
        "reason":                  _build_reason(
                                       college_name=college_name,
                                       branch=branch,
                                       city=city,
                                       cutoff=cutoff,
                                       gap=gap,
                                       tier=tier,
                                       preferred_branch=preferred_branch,
                                       preferred_city=preferred_city,
                                   ),
        # AI explanation placeholder — populated by _attach_ai_explanations()
        "ai_explanation":          "",
        # Extra metadata (available for future use; not breaking the template)
        "score_gap":               gap,
    }


def _build_reason(
    *,
    college_name: str,
    branch: str,
    city: str,
    cutoff: float,
    gap: float,
    tier: str,
    preferred_branch: str,
    preferred_city: str,
) -> str:
    """
    Build a deterministic one-sentence explanation used as the fallback
    when the AI explanation is unavailable.
    """
    parts: list[str] = []

    if tier == "Dream":
        parts.append(
            f"{college_name} is a Dream college — your percentile is only "
            f"{gap:.1f} pts above the {cutoff:.1f} cutoff, so competition is high."
        )
    elif tier == "Moderate":
        parts.append(
            f"{college_name} is a Moderate pick — your percentile clears the "
            f"{cutoff:.1f} cutoff by {gap:.1f} pts, giving a solid chance."
        )
    else:
        parts.append(
            f"{college_name} is a Safe choice — your percentile exceeds the "
            f"{cutoff:.1f} cutoff by {gap:.1f} pts, ensuring high admission probability."
        )

    if branch.lower() == preferred_branch.lower():
        parts.append(f"It offers your preferred branch ({branch}).")
    else:
        parts.append(f"It offers {branch} (related to your interest in {preferred_branch}).")

    if city.lower() == preferred_city.lower():
        parts.append(f"Located in your preferred city, {city}.")
    else:
        parts.append(f"Located in {city}.")

    return " ".join(parts)


# ===========================================================================
# Per-college AI explanation  (IBM Watsonx Granite)
# ===========================================================================

_EXPLANATION_SYSTEM = (
    "You are an AI College Admission Counsellor for Maharashtra engineering students.\n"
    "Write ONE concise sentence (max 40 words) personalised to the student below.\n"
    "Use ONLY the college data provided. Do NOT invent any figures.\n"
    "Tone: encouraging and factual."
)


def _generate_explanation(
    college: dict[str, Any],
    student_data: dict[str, Any],
) -> str:
    """
    Call IBM Watsonx Granite to generate a personalised 1-sentence explanation
    for why this specific college suits this specific student.

    Falls back to the pre-computed rule-based ``reason`` on any error so that
    a single failed API call never breaks the entire recommendations page.

    Parameters
    ----------
    college      : dict  A single recommendation dict from ``_build_result``.
    student_data : dict  The student profile.

    Returns
    -------
    str  The AI explanation, or the rule-based fallback.
    """
    user_msg = (
        f"Student: {student_data.get('name')}, "
        f"Percentile: {student_data.get('cet_percentile')}, "
        f"Category: {student_data.get('category')}, "
        f"Preferred Branch: {student_data.get('preferred_branch')}, "
        f"Preferred City: {student_data.get('preferred_city')}.\n\n"
        f"College: {college['name']}\n"
        f"Branch: {college['branch']}\n"
        f"City: {college['city']}\n"
        f"Cutoff: {college['cutoff']} percentile\n"
        f"Annual Fees: Rs.{college['annual_fees']}\n"
        f"Tier: {college['recommendation_category']}\n"
        f"Match Score: {college['match_score']}/100\n\n"
        f"Write a single personalised sentence explaining why this college suits this student."
    )

    try:
        reply = chat(user_msg, system_prompt=_EXPLANATION_SYSTEM)
        # Guard: if Watsonx returns an error string, fall back gracefully
        if reply.startswith("Watsonx Error"):
            logger.warning("Watsonx returned error for explanation; using rule-based fallback.")
            return college["reason"]
        return reply
    except Exception as exc:
        logger.warning("AI explanation failed for '%s': %s", college["name"], exc)
        return college["reason"]


def _attach_ai_explanations(
    results: list[dict[str, Any]],
    student_data: dict[str, Any],
) -> list[dict[str, Any]]:
    """
    Iterate over every recommendation and populate its ``ai_explanation``
    field by calling ``_generate_explanation``.

    If a call fails, the existing rule-based ``reason`` is used instead —
    no recommendation is lost and the page always renders completely.

    The ``reason`` field is left intact as a fallback and for debugging.
    """
    for college in results:
        college["ai_explanation"] = _generate_explanation(college, student_data)
    return results
